if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "AI-01 source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "AI-01 source contract forbids ${description}: ${needle}")
    endif()
endfunction()

file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CharacterService.h" service_header)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/CharacterService.cpp" service_source)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/AICharacterInspector.cpp" inspector_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeLiveDiagnostics.cpp" runtime_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeApplication.h" runtime_header)

require_text(service_header "CharacterMetadataKey" "versioned Character metadata contract")
require_text(service_header "MakeCharacterCommand" "command-backed MAKE CHARACTER")
require_text(service_header "RemoveCharacterCommand" "command-backed REMOVE CHARACTER")
require_text(service_header "SetCharacterSettingsCommand" "command-backed Character editing")
require_text(service_header "CharacterRuntimeState" "bounded Runtime discovery state")
require_text(service_header "controllerSnapshot_" "exact owned controller restoration snapshot")
require_text(service_header "controllerFootPlacementEnabled_" "nonserialized controller authoring snapshot")
require_text(service_source "AssignPersistentEntityId" "stable Renegade identity assignment")
require_text(service_source "scene_->characters.Create" "native Wicked CharacterComponent binding")
require_text(service_source "character->SetActive(false)" "inactive Studio CharacterComponent")
require_text(service_source "InitializeRuntimeCharacters" "Runtime Character discovery")
require_text(service_source "std::unordered_set<StableId> seenIds" "duplicate stable identity rejection")
require_text(service_source "lhs.characterId < rhs.characterId" "stable-ID Runtime ordering")
require_text(service_source "CharacterPromotionBlockReason" "reserved semantic promotion guard")
require_text(service_source "IsPlayerStart" "Player Start promotion rejection")
require_text(service_source "IsRenegadeNavigationGrid" "navigation grid promotion rejection")
require_text(service_source "IsRenegadeNavigationDestination" "navigation destination promotion rejection")
require_text(service_source "character->Serialize(controllerSnapshot_" "native controller serialization restoration")
require_text(service_source "SetFootPlacementEnabled(controllerFootPlacementEnabled_)" "nonserialized foot-placement restoration")
require_text(inspector_source "MAKE CHARACTER" "creator promotion surface")
require_text(inspector_source "InspectorSectionProvider" "existing Inspector section framework")
require_text(inspector_source "session->Commands().Execute" "Studio CommandService ownership")
require_text(runtime_header "CharacterRuntimeState" "Runtime Character state ownership")
require_text(runtime_header "characterSceneAttemptRevision_" "separate Runtime Character attempt revision")
require_text(runtime_header "characterSceneAttempted_" "revision-zero Runtime Character attempt state")
require_text(runtime_header "characterSceneSyncFailed_" "explicit Runtime Character failure state")
require_text(runtime_source "InitializeRuntimeCharacters" "Runtime scene synchronization")
require_text(runtime_source "ResetRuntimeCharacters" "Runtime Character teardown on non-Level transitions")
require_text(runtime_source "!characterSceneAttempted_" "revision-zero Character discovery")
require_text(runtime_source "characterSceneAttempted_ && !characterSceneSyncFailed_" "truthful Character sync success")
require_text(runtime_source "characterSceneSyncFailed_ = true" "failed Character sync diagnostics")
require_text(runtime_source "scene_sync_failed" "live AI sync-failure diagnostics")
require_text(runtime_source "character_count" "live AI diagnostics registration")

forbid_text(service_source "Recast" "parallel navigation implementation")
forbid_text(service_source "SetPosition(transform->GetPosition());\n            transform" "transform-driven character movement")
forbid_text(inspector_source "UpdateRuntimeCharacters" "production cognition inside Studio")

message(STATUS "PASS: AI-01 Character foundation source contract")
