if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "AI-02 source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "AI-02 source contract forbids ${description}: ${needle}")
    endif()
endfunction()

file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CharacterProfileService.h" profile_source)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/FactionService.h" faction_source)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CharacterService.h" character_header)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/CharacterService.cpp" character_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeCharacterSystem.h" runtime_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeApplication.h" runtime_header)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeLiveDiagnostics.cpp" runtime_diagnostics)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/AICharacterInspector.cpp" inspector_source)
file(READ "${RENEGADE_SOURCE_DIR}/Tests/CharacterAiProfilesTests.cpp" test_source)
file(READ "${RENEGADE_SOURCE_DIR}/Tests/CharacterAiProfilesAuditTests.cpp" audit_test_source)

require_text(profile_source "CharacterProfileRegistryVersion = 1" "versioned built-in profile registry")
require_text(profile_source "CharacterAdvancedSchemaVersion = 1" "versioned advanced override payload")
require_text(profile_source "CharacterAdvancedMetadataKey =" "advanced override persistence key")
require_text(profile_source "CharacterAdvancedPayloadMetadataKey" "single Character-owned advanced metadata key authority")
require_text(profile_source "BuiltInBehaviourProfiles" "built-in behaviour profile registry")
require_text(profile_source "ApplyRole(tuning, settings.role)" "behaviour/role composition layer")
require_text(profile_source "ApplyPersonality(tuning, settings.personality)" "personality composition layer")
require_text(profile_source "ApplySkill(tuning, settings.skill)" "skill composition layer")
require_text(profile_source "ApplyAwareness(tuning, settings.awareness)" "awareness composition layer")
require_text(profile_source "ApplyOverrides(tuning, overrides)" "explicit override composition layer")
require_text(profile_source "ValidateCharacterProfileAuthoring" "raw persisted profile validation")
require_text(profile_source "std::locale::classic()" "locale-neutral advanced serialization")
require_text(profile_source "duplicate field" "duplicate advanced field rejection")
require_text(profile_source "SetCharacterAdvancedOverridesCommand" "command-backed advanced overrides")
require_text(profile_source "rawBefore_" "raw malformed payload recovery snapshot")
require_text(profile_source "beforeParsed_" "well-formed no-op filtering without blocking malformed recovery")
require_text(profile_source "DeserializeCharacterAdvancedOverrides" "advanced override persistence reader")

require_text(faction_source "enum class FactionRelationship" "faction relationship contract")
require_text(faction_source "class FactionRegistry" "known-faction registration service")
require_text(faction_source "ResetToBuiltIns" "deterministic known-faction reset")
require_text(faction_source "KnownFactionIds" "read-only known-faction projection")
require_text(faction_source "Hostile" "hostile faction relationship")
require_text(faction_source "Suspicious" "suspicious faction relationship")
require_text(faction_source "BuiltInFactions" "built-in faction registry")
require_text(faction_source "DefaultFactionRelationship" "relationship matrix")
forbid_text(faction_source "wi::scene::Scene" "perception/scene coupling inside faction semantics")
forbid_text(faction_source "Perception" "perception coupling inside faction semantics")
forbid_text(faction_source "detected" "detection state inside faction semantics")

require_text(character_header "CharacterAdvancedPayloadMetadataKey" "Character-owned advanced payload lifecycle key")
require_text(character_header "advancedMetadataSnapshot_" "REMOVE CHARACTER advanced metadata snapshot")
require_text(character_source "metadata.string_values.erase(CharacterAdvancedPayloadMetadataKey)" "advanced payload removal")
require_text(character_source "hasAdvancedMetadataSnapshot_ = true" "advanced payload history capture")
require_text(character_source "advancedMetadataSnapshot_" "advanced payload Undo restoration")

require_text(runtime_source "ValidateRuntimeCharacterMarkers" "owned Character marker/schema preflight")
require_text(runtime_source "unsupported schema version" "unsupported Character schema failure")
require_text(runtime_source "EntityIdentityIndex" "single stable-reference resolution index")
require_text(runtime_source "FactionRegistry factions" "Runtime known-faction registry")
require_text(runtime_source "ValidateCharacterProfileAuthoring" "fail-closed raw profile validation in Runtime")
require_text(runtime_source "candidate.factions.Register" "creator-defined faction registration during Runtime setup")
require_text(runtime_source "CharacterTuning" "resolved effective tuning in Runtime records")
require_text(runtime_source "CharacterAdvancedOverrides" "resolved advanced overrides in Runtime records")
require_text(runtime_source "CaptureCharacterAdvancedOverrides" "Runtime advanced override resolution")
require_text(runtime_source "patrolRouteEntityId" "stable patrol reference resolution")
require_text(runtime_source "weaponEntityId" "stable weapon reference resolution")
require_text(runtime_source "RelationshipBetween" "Runtime semantic faction lookup")
require_text(runtime_source "does not imply that" "explicit anti-cheat relationship boundary")
require_text(runtime_source "state = {}" "fail-closed published Runtime state")
forbid_text(runtime_source "Recast" "parallel navigation implementation")
forbid_text(runtime_source "SetPosition" "transform/native movement inside AI-02 state setup")
forbid_text(runtime_source "GameplayEventService" "AI-02 event bus")

require_text(runtime_header "RuntimeCharacterSystemState characterAiState_" "Runtime ownership of transient resolved Character state")
require_text(runtime_diagnostics "InitializeRuntimeCharacterSystem" "AI-02 integration into real Runtime scene sync")
require_text(runtime_diagnostics "ResetRuntimeCharacterSystem(characterAiState_)" "deterministic AI-02 Runtime reset")
require_text(runtime_diagnostics "character.profile.failed" "profile/reference setup failure diagnostics")
require_text(runtime_diagnostics "profile_registry_version" "AI-02 bounded diagnostic evidence")
require_text(runtime_diagnostics "characterAiState_.characters.size() == characterState_.characters.size()" "combined AI-01/AI-02 scene sync truth")

require_text(inspector_source "Character Skill" "creator-facing skill preset")
require_text(inspector_source "Character Awareness" "creator-facing awareness preset")
require_text(inspector_source "ADVANCED AI" "collapsed advanced AI creator section")
require_text(inspector_source "PERCEPTION" "grouped advanced perception controls")
require_text(inspector_source "MEMORY" "grouped advanced memory controls")
require_text(inspector_source "PERSONALITY" "grouped advanced personality controls")
require_text(inspector_source "COMBAT" "grouped advanced combat controls")
require_text(inspector_source "COMMUNICATION" "grouped advanced communication controls")
require_text(inspector_source "SetCharacterAdvancedOverridesCommand" "command-backed Studio advanced edits")
require_text(inspector_source "ValidateFactionId" "creator-defined faction validation")
require_text(inspector_source "animationSet_.OnInputAccepted" "single accepted Animation Set text commit")
require_text(inspector_source "customFaction_.OnInputAccepted" "single accepted custom faction text commit")
require_text(inspector_source "SetExpanded(AICharacterAdvancedSectionId, true)" "wired custom faction picker route")
require_text(inspector_source "ADVANCED AI INVALID // RESET OVERRIDES" "visible malformed advanced authoring state")
require_text(inspector_source "resetAdvanced_.SetEnabled(true)" "malformed advanced repair surface")
forbid_text(inspector_source "UpdateRuntimeCharacters" "Runtime cognition inside Studio")

require_text(test_source "advanced override serialization was not deterministic" "advanced payload parser round trip")
require_text(test_source "native WISCENE serialization" "advanced authoring WISCENE round trip")
require_text(test_source "creator-defined faction registration was not deterministic" "creator faction registry regression")
require_text(test_source "missing Character reference did not fail closed" "missing-reference regression")
require_text(test_source "Runtime faction relationship did not resolve independently of perception" "relationship/perception separation regression")
require_text(test_source "advanced override Undo" "advanced override history regression")
require_text(test_source "REMOVE CHARACTER leaked AI-02 advanced metadata" "advanced metadata removal regression")

require_text(audit_test_source "unsupported Character schema marker was silently ignored" "unsupported schema marker regression")
require_text(audit_test_source "malformed raw profile enum did not fail closed" "raw enum corruption regression")
require_text(audit_test_source "duplicate advanced field did not fail closed" "duplicate field corruption regression")
require_text(audit_test_source "locale-neutral and deterministic" "locale-neutral payload regression")
require_text(audit_test_source "RESET ADVANCED could not repair malformed payload" "malformed payload recovery regression")
require_text(audit_test_source "advanced repair Undo did not restore exact raw payload" "raw recovery Undo regression")

message(STATUS "PASS: AI-02 profiles/factions/runtime source contract")
