if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(PERCEPTION "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeCharacterPerception.h")
set(RUNTIME_DIAGNOSTICS "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeLiveDiagnostics.cpp")
set(RUNTIME_HEADER "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeApplication.h")

foreach(path IN LISTS PERCEPTION RUNTIME_DIAGNOSTICS RUNTIME_HEADER)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "AI-03 required source is missing: ${path}")
    endif()
endforeach()

file(READ "${PERCEPTION}" PERCEPTION_TEXT)
file(READ "${RUNTIME_DIAGNOSTICS}" DIAGNOSTICS_TEXT)
file(READ "${RUNTIME_HEADER}" RUNTIME_HEADER_TEXT)

function(require_text haystack needle label)
    string(FIND "${haystack}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "AI-03 source contract missing ${label}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle label)
    string(FIND "${haystack}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "AI-03 source contract forbids ${label}: ${needle}")
    endif()
endfunction()

require_text("${PERCEPTION_TEXT}" "CharacterCognitionIntervalSeconds = 0.20f" "5 Hz cognition cadence")
require_text("${PERCEPTION_TEXT}" "MaxSoundStimuli = 128" "bounded sound queue")
require_text("${PERCEPTION_TEXT}" "MaxCharacterMemories = 16" "bounded per-character memory")
require_text("${PERCEPTION_TEXT}" "KnowledgeSource::Seen" "Seen knowledge source")
require_text("${PERCEPTION_TEXT}" "KnowledgeSource::Heard" "Heard knowledge source")
require_text("${PERCEPTION_TEXT}" "KnowledgeSource::DamagedBy" "damage attribution knowledge source")
require_text("${PERCEPTION_TEXT}" "AwarenessState::Searching" "Searching awareness state")
require_text("${PERCEPTION_TEXT}" "if (!observation.visible)" "hidden-observation anti-cheat branch")
require_text("${PERCEPTION_TEXT}" "GetPhysicsPosition(scene, player.entity" "physics-authoritative player position")
require_text("${PERCEPTION_TEXT}" "scene.Intersects(" "native Wicked line-of-sight query")
require_text("${PERCEPTION_TEXT}" "EntityBelongsToRoot" "observer hierarchy self-hit rejection")
require_text("${PERCEPTION_TEXT}" "EmitPlayerFootstepStimulus" "explicit player footstep sound stimulus")
require_text("${PERCEPTION_TEXT}" "ReportDamageStimulus" "damage attribution seam")
require_text("${PERCEPTION_TEXT}" "pendingVisualSeconds" "visual reaction latency")
require_text("${PERCEPTION_TEXT}" "pendingSoundReadyTime" "audio reaction latency")
require_text("${PERCEPTION_TEXT}" "StableHash(character.stableEntityId)" "stable-ID cognition staggering")
require_text("${PERCEPTION_TEXT}" "lastKnownPosition" "last-known memory")
require_text("${PERCEPTION_TEXT}" "memory.confidence" "memory confidence decay")
require_text("${PERCEPTION_TEXT}" "FiniteVector" "stimulus finite-value validation")
require_text("${PERCEPTION_TEXT}" "ValidSubjectId" "bounded stimulus identity validation")

# The Runtime player is a Wicked character-physics rigid body, not a native
# Scene::characters CharacterComponent. AI-03 must keep using the accepted
# physics-position seam rather than reintroducing the lost-checkpoint mistake.
forbid_text("${PERCEPTION_TEXT}" "scene.characters.GetComponent(player.entity)" "player-as-CharacterComponent lookup")
forbid_text("${PERCEPTION_TEXT}" "scene.transforms.GetComponent(player.entity)" "hidden player transform fallback")

require_text("${DIAGNOSTICS_TEXT}" "InitializeRuntimeCharacterPerception" "transactional AI-03 initialization")
require_text("${DIAGNOSTICS_TEXT}" "UpdateRuntimeCharacterPerception" "Runtime cognition integration")
require_text("${DIAGNOSTICS_TEXT}" "ResetRuntimeCharacterPerception" "Runtime cognition teardown")
require_text("${DIAGNOSTICS_TEXT}" "playerSceneRevision_ == sceneRevision" "stale-player scene guard")
require_text("${DIAGNOSTICS_TEXT}" "first_knowledge_source" "knowledge-source diagnostics")
require_text("${DIAGNOSTICS_TEXT}" "first_last_known_position" "last-known diagnostics")
require_text("${DIAGNOSTICS_TEXT}" "los_queries" "LOS-budget diagnostics")
require_text("${DIAGNOSTICS_TEXT}" "sound_queue_depth" "sound-queue diagnostics")
require_text("${RUNTIME_HEADER_TEXT}" "RuntimeCharacterPerceptionState characterPerceptionState_" "Runtime transient perception ownership")

message(STATUS "AI-03 perception source contract passed")
