if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "AI-01 source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "AI-01 source contract forbids ${description}: ${needle}")
    endif()
endfunction()

file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CharacterService.h" service_header)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/CharacterService.cpp" service_source)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/AICharacterInspector.cpp" inspector_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeLiveDiagnostics.cpp" runtime_source)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeApplication.h" runtime_header)

require_text(service_header "CharacterMetadataKey" "versioned Character metadata contract")
require_text(service_header "MakeCharacterCommand" "command-backed MAKE CHARACTER")
require_text(service_header "RemoveCharacterCommand" "command-backed REMOVE CHARACTER")
require_text(service_header "SetCharacterSettingsCommand" "command-backed Character editing")
require_text(service_header "CharacterRuntimeState" "bounded Runtime discovery state")
require_text(service_source "AssignPersistentEntityId" "stable Renegade identity assignment")
require_text(service_source "scene_->characters.Create" "native Wicked CharacterComponent binding")
require_text(service_source "character->SetActive(false)" "inactive Studio CharacterComponent")
require_text(service_source "InitializeRuntimeCharacters" "Runtime Character discovery")
require_text(inspector_source "MAKE CHARACTER" "creator promotion surface")
require_text(inspector_source "InspectorSectionProvider" "existing Inspector section framework")
require_text(inspector_source "session->Commands().Execute" "Studio CommandService ownership")
require_text(runtime_header "CharacterRuntimeState" "Runtime Character state ownership")
require_text(runtime_source "InitializeRuntimeCharacters" "Runtime scene synchronization")
require_text(runtime_source "character_count" "live AI diagnostics registration")

forbid_text(service_source "Recast" "parallel navigation implementation")
forbid_text(service_source "SetPosition(transform->GetPosition());\n            transform" "transform-driven character movement")
forbid_text(inspector_source "UpdateRuntimeCharacters" "production cognition inside Studio")

message(STATUS "PASS: AI-01 Character foundation source contract")
