if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(read_required relative_path output_name)
    set(path "${RENEGADE_SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "AI-05 source contract missing ${relative_path}")
    endif()
    file(READ "${path}" content)
    set(${output_name} "${content}" PARENT_SCOPE)
endfunction()

function(require_text haystack needle description)
    string(FIND "${haystack}" "${needle}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "AI-05 source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle description)
    string(FIND "${haystack}" "${needle}" index)
    if(NOT index EQUAL -1)
        message(FATAL_ERROR "AI-05 source contract forbids ${description}: ${needle}")
    endif()
endfunction()

read_required("EngineBridge/include/renegade/bridge/WeaponCombatService.h" weapon)
read_required("Runtime/src/RuntimeCombatService.h" combat)
read_required("Runtime/src/RuntimeCombatDecision.h" decision)
read_required("Runtime/src/RuntimeApplication.h" app)
read_required("Tests/CharacterAiCombatTests.cpp" tests)

require_text("${weapon}" "WeaponAiDescriptor" "reusable weapon descriptor")
require_text("${weapon}" "CaptureWeaponAiDescriptor" "governed/fallback weapon resolution")
require_text("${weapon}" "WeaponAiSchemaVersion" "versioned weapon metadata")
require_text("${weapon}" "magazineSize" "bounded magazine semantics")
require_text("${weapon}" "reloadSeconds" "reload timing semantics")
require_text("${weapon}" "baseAccuracy" "AI accuracy semantics")

require_text("${combat}" "RuntimeCombatState" "Runtime-owned combat state")
require_text("${combat}" "nativeCharacter->health" "native Wicked NPC health seam")
require_text("${combat}" "DeterministicCombatUnit" "deterministic bounded hit resolution")
require_text("${combat}" "ComputeCombatHitChance" "range/accuracy hit model")
require_text("${combat}" "BeginCombatReload" "reload state transition")
require_text("${combat}" "TryFireAtRuntimePlayer" "reusable firing seam")
require_text("${combat}" "EmitSoundStimulus" "weapon sound feeds legitimate perception")
require_text("${combat}" "GameplayEventService" "existing gameplay event authority")

require_text("${decision}" "ScoreCharacterCombatIntents" "combat utility scoring")
require_text("${decision}" "CharacterIntent::Attack" "Attack intent")
require_text("${decision}" "CharacterIntent::Reload" "Reload intent")
require_text("${decision}" "CharacterIntent::Retreat" "Retreat intent")
require_text("${decision}" "CharacterIntent::Flee" "Flee intent")
require_text("${decision}" "CharacterIntent::Surrender" "Surrender intent")
require_text("${decision}" "memory->lastKnownPosition" "memory-derived combat escape")
require_text("${decision}" "SetCharacterNavigationGoal" "native navigation for escape")
require_text("${decision}" "nativeCharacter->Turn(direction)" "native Character turning")
require_text("${decision}" "nativeCharacter->Move(XMFLOAT3(" "native Character movement")

forbid_text("${decision}" ".Translate(" "transform-driven combat movement")
forbid_text("${decision}" "GetPhysicsPosition" "hidden live target lookup in combat decision")
forbid_text("${decision}" "recast" "second navigation stack")
forbid_text("${combat}" "std::rand" "frame/global RNG combat resolution")

require_text("${app}" "RuntimeCombatState combatState_" "Runtime combat ownership")
require_text("${app}" "GameplayEventService combatEventService_" "existing event-service instance")

require_text("${tests}" "NPC native health synchronization" "native health regression")
require_text("${tests}" "reload ammo transfer" "reload regression")
require_text("${tests}" "flee goal must move away from remembered hostile position" "memory-only escape regression")
require_text("${tests}" "publish GameplayEventService event" "combat event regression")

message(STATUS "AI-05 combat source contract passed")
