if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(read_required relative_path output_name)
    set(path "${RENEGADE_SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "AI-04 source contract missing ${relative_path}")
    endif()
    file(READ "${path}" content)
    set(${output_name} "${content}" PARENT_SCOPE)
endfunction()

function(require_text haystack needle description)
    string(FIND "${haystack}" "${needle}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "AI-04 source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text haystack needle description)
    string(FIND "${haystack}" "${needle}" index)
    if(NOT index EQUAL -1)
        message(FATAL_ERROR "AI-04 source contract forbids ${description}: ${needle}")
    endif()
endfunction()

read_required("EngineBridge/include/renegade/bridge/PatrolRouteService.h" route)
read_required("EngineBridge/include/renegade/bridge/CharacterPatrolRouteCommand.h" character_patrol)
read_required("Runtime/src/RuntimeCharacterDecision.h" decision)
read_required("Runtime/src/RuntimeLiveDiagnostics.cpp" runtime)
read_required("Studio/src/AIPatrolRouteInspector.cpp" patrol_inspector)
read_required("Studio/src/Phase7Gate7AAnimationInspector.h" inspector_stack)
read_required("Studio/MarkerIcons.cmake" studio_sources)
read_required("CMakeLists.txt" root_build_sources)
string(APPEND studio_sources "${root_build_sources}")
read_required("Tests/CharacterAiDecisionTests.cpp" tests)

require_text("${route}" "PatrolRouteMetadataKey" "persistent Patrol Route metadata")
require_text("${route}" "PatrolRoutePointMetadataKey" "persistent Patrol Point metadata")
require_text("${route}" "AssignPersistentEntityId" "stable patrol identities")
require_text("${route}" "Loop = 0" "loop traversal mode enum")
require_text("${route}" "PingPong = 1" "ping-pong traversal mode enum")
require_text("${route}" "Random = 2" "random traversal mode enum")
require_text("${route}" "CreatePatrolRouteCommand" "command-backed route creation")
require_text("${route}" "AddPatrolRoutePointCommand" "command-backed point creation")
require_text("${character_patrol}" "CreateCharacterPatrolRouteCommand" "atomic creator route creation and assignment")
require_text("${character_patrol}" "after.patrolRouteEntityId = routeCommand_.CreatedStableId()" "stable-id character route assignment")
require_text("${character_patrol}" "routeCommand_.Undo()" "failed/undone creator route rollback")

require_text("${decision}" "ScoreCharacterIntents" "utility-scored decision layer")
require_text("${decision}" "CharacterDecisionHysteresisBonus" "decision hysteresis")
require_text("${decision}" "CharacterDecisionCommitmentSeconds" "decision commitment")
require_text("${decision}" "BestActionableMemory" "AI-03 memory consumption")
require_text("${decision}" "memory->lastKnownPosition" "last-known-position goals")
require_text("${decision}" "case bridge::PatrolRouteMode::PingPong:" "ping-pong traversal execution")
require_text("${decision}" "case bridge::PatrolRouteMode::Random:" "random traversal execution")
require_text("${decision}" "SetCharacterNavigationGoal" "native NavigationService goal submission")
require_text("${decision}" "character->pathquery.get_next_waypoint()" "native Wicked path ownership")
require_text("${decision}" "character->Turn(direction)" "native CharacterComponent turning")
require_text("${decision}" "character->Move(XMFLOAT3(" "native CharacterComponent movement")
require_text("${decision}" "Search timeout -> return to role" "return-to-role behavior")
require_text("${decision}" "Stuck recovery requested native repath; no teleport used" "non-teleport stuck recovery")
require_text("${decision}" "StableRandomPatrolIndex" "deterministic random patrol")
require_text("${decision}" "IsSearchMemoryExhausted" "bounded stale-memory search exhaustion")
require_text("${decision}" "RefreshSearchExhaustion" "fresh legitimate stimulus search reset")

forbid_text("${decision}" ".Translate(" "transform-driven Runtime movement")
forbid_text("${decision}" "SetPosition(" "transform-driven Runtime position writes")
forbid_text("${decision}" "RuntimePlayerState" "direct live-player dependency in decision layer")
forbid_text("${decision}" "GetPhysicsPosition" "hidden live target lookup in decision layer")
forbid_text("${decision}" "recast" "second navigation stack")

require_text("${runtime}" "InitializeRuntimeCharacterDecision" "fail-closed AI-04 scene initialization")
require_text("${runtime}" "UpdateRuntimeCharacterDecision" "Runtime-owned AI-04 update")
require_text("${runtime}" "first_intent" "intent diagnostics")
require_text("${runtime}" "first_top_utility_scores" "decision-score diagnostics")

require_text("${patrol_inspector}" "CREATE + ASSIGN ROUTE" "creator Patrol Route workflow")
require_text("${patrol_inspector}" "AddPatrolRoutePointCommand" "creator Patrol Point authoring")
require_text("${patrol_inspector}" "SetPatrolRouteSettingsCommand" "command-backed Patrol Route settings")
require_text("${inspector_stack}" "RegisterAIPatrolRouteInspector" "Patrol Inspector registration")
require_text("${inspector_stack}" "PrepareAIPatrolRouteInspector" "Patrol Inspector layout lifecycle")
require_text("${studio_sources}" "src/AIPatrolRouteInspector.cpp" "Patrol Inspector Studio build registration")

require_text("${tests}" "last-known position" "anti-cheat decision regression")
require_text("${tests}" "stale exhausted memory must return to normal role" "search exhaustion regression")
require_text("${tests}" "fresh legitimate memory must clear search exhaustion" "fresh stimulus search regression")

message(STATUS "AI-04 decision/patrol source contract passed")
