# Source-geometry regression: the Review stage must leave thumbnail capture
# and Confirm Import reachable below the asset destination, without overlap.
if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.cpp" importer)
foreach(field IN ITEMS reviewTitleY reviewPreviewY)
    string(REGEX MATCH "const float ${field} = ([0-9]+)\\.0f;" match "${importer}")
    if(NOT match)
        message(FATAL_ERROR "Importer Review ${field} has no literal layout anchor")
    endif()
    set(${field} "${CMAKE_MATCH_1}")
endforeach()
string(REGEX MATCH "creatorImportDestination.SetPos\\(XMFLOAT2\\(12\\.0f, ([0-9]+)\\.0f\\)\\);" dest_position "${importer}")
if(NOT dest_position)
    message(FATAL_ERROR "Importer destination position missing")
endif()
set(destinationTop "${CMAKE_MATCH_1}")
string(REGEX MATCH "creatorImportDestination.SetSize\\(XMFLOAT2\\(importScalePanelWidth - 24\\.0f, ([0-9]+)\\.0f\\)\\);" dest_size "${importer}")
if(NOT dest_size)
    message(FATAL_ERROR "Importer destination height missing")
endif()
set(destinationHeight "${CMAKE_MATCH_1}")
math(EXPR destinationBottom "${destinationTop} + ${destinationHeight}")
math(EXPR minimumTitle "${destinationBottom} + 8")
if(reviewTitleY LESS minimumTitle)
    message(FATAL_ERROR "Importer Review title overlaps asset destination")
endif()
math(EXPR minimumPreview "${reviewTitleY} + 28 + 8")
if(reviewPreviewY LESS minimumPreview)
    message(FATAL_ERROR "Importer thumbnail preview overlaps Review title")
endif()
string(REGEX MATCH "340\\.0f, animationBodyHeight, ([0-9]+)\\.0f" review_body "${importer}")
if(NOT review_body)
    message(FATAL_ERROR "Importer Review scroll-body height missing")
endif()
set(reviewBodyHeight "${CMAKE_MATCH_1}")
# 244 is the thumbnail's maximum side; remaining spacings and button heights
# correspond to the actual Review stage layout in StudioApplication.cpp.
math(EXPR cancelBottom "${reviewPreviewY} + 244 + 14 + 48 + 46 + 52 + 34")
math(EXPR availableBottom "184 + ${reviewBodyHeight} - 8")
if(cancelBottom GREATER availableBottom)
    message(FATAL_ERROR "Importer Review final action exceeds scroll-body bounds")
endif()
message(STATUS "Importer Review layout contract passed: destination, thumbnail and final actions")
