set(marker_source "${RENEGADE_SOURCE_DIR}/Studio/src/MarkerIconOverlay.cpp")
set(marker_cmake "${RENEGADE_SOURCE_DIR}/Studio/MarkerIcons.cmake")
set(diagnostics "${RENEGADE_SOURCE_DIR}/Studio/src/StudioLiveDiagnostics.cpp")
set(root_cmake "${RENEGADE_SOURCE_DIR}/CMakeLists.txt")

foreach(required IN ITEMS "${marker_source}" "${marker_cmake}" "${diagnostics}" "${root_cmake}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "MarkerIcons integration file missing: ${required}")
    endif()
endforeach()

file(READ "${marker_source}" marker_text)
file(READ "${marker_cmake}" marker_cmake_text)
file(READ "${diagnostics}" diagnostics_text)
file(READ "${root_cmake}" root_cmake_text)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "MarkerIcons contract failed: ${description}")
    endif()
endfunction()

function(reject_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "MarkerIcons contract failed: ${description}")
    endif()
endfunction()

require_text(marker_text "projectRoot" "project override seam")
require_text(marker_text "fs::path(\"User\") / \"MarkerIcons\"" "user override seam")
require_text(marker_text "fs::path(\"Content\") / \"Editor\" / \"MarkerIcons\"" "stock fallback seam")
require_text(marker_text "ParticleEmitter" "particle marker registration")
require_text(marker_text "ScriptEntity" "script marker registration")
require_text(marker_text "constexpr float MarkerSize = 96.0f" "owner-approved 200 percent marker size")
require_text(marker_text "SetEnabled(true)" "interactive marker overlay")
require_text(marker_text "session->Selection().Select(candidate)" "viewport marker click selection")
require_text(marker_text "bestDistance2" "overlapping marker nearest-centre selection")
require_text(marker_cmake_text "MarkerIconOverlay.cpp" "marker overlay Studio registration")
reject_text(marker_cmake_text "copy_directory" "binary marker artwork must not be copied by CMake")
reject_text(marker_cmake_text "Studio/assets/markericons" "binary marker artwork must not be sourced from the repository")
require_text(diagnostics_text "EnsureMarkerIconOverlay(*this);" "frame lifecycle registration")
require_text(root_cmake_text "include(Studio/MarkerIcons.cmake)" "root build registration")
