if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(workspace_v3 "${RENEGADE_SOURCE_DIR}/Studio/src/RenegadeParticleEmitterWorkspaceV3.cpp")
set(particle_cmake "${RENEGADE_SOURCE_DIR}/Studio/ParticleEmitter.cmake")

foreach(required IN ITEMS "${workspace_v3}" "${particle_cmake}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "Particle owner-feedback contract missing ${required}")
    endif()
endforeach()

file(READ "${workspace_v3}" workspace_text)
file(READ "${particle_cmake}" particle_cmake_text)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Particle owner-feedback contract failed: ${description}")
    endif()
endfunction()

require_text(workspace_text "NumericHitGutter" "numeric input safety gutter")
require_text(workspace_text "insideValueBox" "exclusive numeric value hit test")
require_text(workspace_text "insideSafetyGutter" "non-slider safety gutter hit test")
require_text(workspace_text "SetAsActive(true)" "single-click exact numeric editing")
require_text(workspace_text "wi::gui::Widget::Update(canvas, dt)" "numeric press bypasses Slider update")
require_text(workspace_text "ParticleInspectorComboBox" "particle-local combo ownership wrapper")
require_text(workspace_text "BlocksInteractionFor" "open combo blocks click-through")
require_text(workspace_text "PopupOpenForOtherControl" "open combo owns render layer")
require_text(workspace_text "RenegadeComboBox::Render(canvas, cmd)" "opaque Renegade combo popup renderer retained")
require_text(workspace_text "GetName() == \"Particle Frame Rate\"" "animation FPS field remains creator-editable at Wicked zero sentinel")
require_text(workspace_text "valueInputField.SetEnabled(true)" "animation FPS exact-value box remains enabled in over-lifetime mode")
require_text(workspace_text "RenegadeSlider::SetEnabled(true)" "animation FPS slider remains enabled in over-lifetime mode")
require_text(workspace_text "RenegadeParticleEmitterWorkspaceV2.cpp" "accepted V2 feature implementation reused")
require_text(particle_cmake_text "RenegadeParticleEmitterWorkspaceV3.cpp" "V3 owner-feedback shim compiled")
require_text(particle_cmake_text "RenegadeParticleEmitterOwnerFeedbackSourceContract" "owner-feedback regression registered")

string(FIND "${particle_cmake_text}" "target_sources(RenegadeStudio PRIVATE\n    \"${CMAKE_CURRENT_LIST_DIR}/src/RenegadeParticleEmitterWorkspaceV2.cpp\"" stale_target)
if(NOT stale_target EQUAL -1)
    message(FATAL_ERROR "Particle owner-feedback contract failed: V2 must not be compiled directly beside V3")
endif()
