if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(blend_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/ParticleBlendModeService.h")
set(blend_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/ParticleBlendModeService.cpp")
set(effect_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/ParticleEffectService.h")
set(effect_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/ParticleEffectService.cpp")
set(library_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/ParticleEffectLibraryService.h")
set(library_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/ParticleEffectLibraryService.cpp")
set(marker_source "${RENEGADE_SOURCE_DIR}/Studio/src/MarkerIconOverlay.cpp")
set(test_source "${RENEGADE_SOURCE_DIR}/Tests/ParticleVfxFollowupTests.cpp")

foreach(required IN ITEMS
    "${blend_header}" "${blend_source}" "${effect_header}" "${effect_source}"
    "${library_header}" "${library_source}" "${marker_source}" "${test_source}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "Particle VFX follow-up source missing ${required}")
    endif()
endforeach()

file(READ "${blend_source}" blend_text)
file(READ "${effect_source}" effect_text)
file(READ "${library_source}" library_text)
file(READ "${marker_source}" marker_text)
file(READ "${test_source}" test_text)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Particle VFX follow-up contract failed: ${description}")
    endif()
endfunction()

require_text(blend_text "material->GetBlendMode()" "native Wicked material blend capture")
require_text(blend_text "ApplyMaterial(*material, state)" "blend changes reuse governed material application")
require_text(effect_text "Entity_CreateEmitter" "effect layers remain native Wicked emitters")
require_text(effect_text "Component_Attach" "effect layers use native Wicked hierarchy")
require_text(effect_text "ParticleEffectRootMetadataKey" "effect root metadata")
require_text(effect_text "AssignNewPersistentEntityId" "effect hierarchy persistent identity")
require_text(library_text "ParticleEffectLibraryFormat" "versioned reusable effect manifest")
require_text(library_text "PrepareMaterialTextureAsset" "governed texture bundling")
require_text(library_text "textures" "self-contained preset texture package")
require_text(library_text "BLENDMODE_COUNT" "native blend mode persistence")
require_text(marker_text "session->Selection().Select(candidate)" "clickable viewport markers")
require_text(marker_text "bestDistance2" "overlapping marker selection policy")
require_text(test_text "Bonfire Reusable" "multi-emitter reusable-effect regression")
require_text(test_text "BLENDMODE_ADDITIVE" "additive blend-mode regression")
require_text(test_text "framesX = 8" "animated 8x8 spritesheet regression")
