file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/RenderSettingsService.h" render_header)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/RenderSettingsService.cpp" render_source)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.h" studio_header)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.cpp" studio_source)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/Phase5Gate5RenderWorkspace.cpp" render_workspace)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/Phase5Gate7RayPathTracing.cpp" gate7_studio)

function(require_text haystack needle message_text)
    string(FIND "${${haystack}}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "${message_text}")
    endif()
endfunction()

require_text(render_header "RenderSettingsSchemaVersion = 3" "Gate 7 render schema is not v3")
require_text(render_header "RTAO = 4" "Gate 7 RTAO state missing")
require_text(render_source "schema < 1 || schema > RenderSettingsSchemaVersion" "Gate 7 legacy schema migration guard missing")
require_text(render_source "setRaytracedReflectionsEnabled" "Gate 7 RT reflections native setter missing")
require_text(render_source "setRaytracedDiffuseEnabled" "Gate 7 RT diffuse native setter missing")
require_text(render_source "SetRaytracedShadowsEnabled" "Gate 7 RT shadows native setter missing")
require_text(render_source "SetSurfelGIEnabled" "Gate 7 Surfel GI native setter missing")
require_text(render_source "GraphicsDeviceCapability::RAYTRACING" "Gate 7 hardware capability guard missing")
require_text(studio_header "public wi::RenderPath3D_PathTracing" "Studio does not derive from pinned Wicked path tracer")
require_text(studio_source "RenderPath3D_PathTracing::Update(dt)" "Path trace Update routing missing")
require_text(studio_source "RenderPath3D_PathTracing::Render()" "Path trace Render routing missing")
require_text(studio_source "RenderPath3D_PathTracing::Compose(cmd)" "Path trace Compose routing missing")
require_text(studio_source "RenderPath3D_PathTracing::ResizeBuffers()" "Path trace ResizeBuffers routing missing")
require_text(gate7_studio "setTargetSampleCount" "Path trace target sample hook missing")
require_text(gate7_studio "resetProgress" "Path trace restart hook missing")
require_text(gate7_studio "SetRaytraceBounceCount" "Path trace bounce hook missing")
require_text(gate7_studio "getCurrentSampleCount" "Path trace progress hook missing")
require_text(gate7_studio "isDenoiserAvailable" "Path trace denoiser status hook missing")
require_text(render_workspace "CreateGate7RenderControls();" "Gate 7 RENDER controls are not attached")
require_text(render_workspace "LayoutGate7RenderControls(fieldWidth, y);" "Gate 7 RENDER controls are not laid out")
require_text(render_workspace "renderWorkspacePanel_.SetEnabled(true);" "Gate 5 child-enable regression guard lost")
require_text(render_workspace "renderWorkspacePanel_.SetVisible(false);" "RENDER final hide missing")

string(FIND "${render_workspace}" "CreateGate7RenderControls();" gate7_create)
string(FIND "${render_workspace}" "renderWorkspacePanel_.SetVisible(false);" render_hide)
if(gate7_create EQUAL -1 OR render_hide EQUAL -1 OR render_hide LESS gate7_create)
    message(FATAL_ERROR "Gate 7 controls are hidden before child attachment completes")
endif()

message(STATUS "Phase 5 Gate 7 source contract passed")
