if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_file path label)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 7D missing ${label}: ${path}")
    endif()
endfunction()

function(require_text text needle label)
    string(FIND "${text}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Phase 7D source contract missing ${label}: ${needle}")
    endif()
endfunction()

function(forbid_text text needle label)
    string(FIND "${text}" "${needle}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "Phase 7D source contract forbids ${label}: ${needle}")
    endif()
endfunction()

set(service_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/AnimationTimelineService.h")
set(service_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/AnimationTimelineService.cpp")
set(inspector_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7DNativeTimelineInspector.h")
set(inspector_source "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7DNativeTimelineInspector.cpp")
set(animation_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7AAnimationInspector.h")
set(root_cmake "${RENEGADE_SOURCE_DIR}/CMakeLists.txt")

require_file("${service_header}" "timeline service header")
require_file("${service_source}" "timeline service source")
require_file("${inspector_header}" "timeline inspector header")
require_file("${inspector_source}" "timeline inspector source")

file(READ "${service_header}" service_h)
file(READ "${service_source}" service)
file(READ "${inspector_source}" inspector)
file(READ "${animation_header}" animation)
file(READ "${root_cmake}" root)

require_text("${service_h}" "AnimationComponent::AnimationChannel::Path" "native channel path authority")
require_text("${service_h}" "AnimationComponent::AnimationSampler::Mode" "native sampler authority")
require_text("${service_h}" "CreateTimelineAnimationCommand" "creator native clip creation")
require_text("${service}" "scene_->animation_datas.Create" "native AnimationDataComponent creation")
require_text("${service}" "InsertOrReplaceKey" "chronological insert-or-replace authoring")
require_text("${service}" "std::lower_bound" "chronological native key insertion")
require_text("${service}" "ReorderKeys" "legacy unsorted-key normalization")
require_text("${service}" "channel.next_event = 0" "event cursor reset after authoring")
require_text("${service}" "PathDataType::Event" "event-aware loop closure")
require_text("${service}" "A loop seam is a value-continuity operation" "event exclusion rationale")
require_text("${service}" "AnimationPath::TRANSLATION" "transform translation recording")
require_text("${service}" "AnimationPath::ROTATION" "transform rotation recording")
require_text("${service}" "AnimationPath::SCALE" "transform scale recording")
require_text("${service}" "AnimationPath::WEIGHTS" "morph weight recording")
require_text("${service}" "AnimationPath::LIGHT_COLOR" "light recording")
require_text("${service}" "AnimationPath::SOUND_PLAY" "sound event recording")
require_text("${service}" "AnimationPath::EMITTER_EMITCOUNT" "emitter recording")
require_text("${service}" "AnimationPath::CAMERA_FOV" "camera recording")
require_text("${service}" "governed .rscripts runtime" "governed script-boundary rejection")
require_text("${service}" "AnimationPath::MATERIAL_COLOR" "material recording")
require_text("${service}" "RecordTimelineKeyCommand" "command-backed native recording")
require_text("${service}" "MoveTimelineKeyCommand" "command-backed key retiming")
require_text("${service}" "DeleteTimelineKeyCommand" "command-backed key deletion")
require_text("${service}" "CloseTimelineLoopCommand" "native close-loop authoring")
require_text("${service}" "SetTimelineSamplerModeCommand" "native sampler authoring")
require_text("${service}" "cubic spline creation is not supported" "safe imported cubic handling")
forbid_text("${service}" "scene.scripts.GetComponent(target)" "Wicked ScriptComponent as Renegade creator-script authority")

require_text("${inspector}" "TIMELINE / KEYFRAMES" "creator timeline section")
require_text("${inspector}" "NEW CLIP" "creator native clip creation action")
require_text("${inspector}" "RECORD KEY" "creator record action")
require_text("${inspector}" "CLOSE LOOP" "creator close-loop action")
require_text("${inspector}" "DELETE KEY" "creator key deletion")
require_text("${inspector}" "CUBIC SPLINE (IMPORTED)" "imported cubic disclosure")
require_text("${inspector}" "RecordExecuted" "Renegade command history ownership")
forbid_text("${inspector}" "append(scene.scripts)" "Wicked ScriptComponent target picker")
forbid_text("${inspector}" "TimelineRecordPreset::ScriptPlay" "misleading native script-play creator preset")
forbid_text("${inspector}" "TimelineRecordPreset::ScriptStop" "misleading native script-stop creator preset")
require_text("${animation}" "RegisterPhase7Gate7DNativeTimelineInspector" "7D inspector registration")
require_text("${animation}" "PreparePhase7Gate7DNativeTimelineInspector" "7D layout preparation")
require_text("${root}" "AnimationTimelineService.cpp" "7D EngineBridge target ownership")
require_text("${root}" "Phase7Gate7DNativeTimelineInspector.cpp" "7D Studio target ownership")
require_text("${root}" "include(Tests/Phase7Gate7D.cmake)" "7D test registration")

foreach(stock_header IN ITEMS "AnimationWindow.h" "EditorComponent.h")
    string(FIND "${inspector}" "${stock_header}" stock_window)
    if(NOT stock_window EQUAL -1)
        message(FATAL_ERROR "Phase 7D must not embed Wicked stock editor UI: ${stock_header}")
    endif()
endforeach()

message(STATUS "Phase 7D repaired native timeline/keyframe source contract passed")
