cmake_minimum_required(VERSION 3.19)

function(read_required relative out_var)
    set(path "${RENEGADE_SOURCE_DIR}/${relative}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Gate 8 required source is missing: ${relative}")
    endif()
    file(READ "${path}" content)
    set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(require_text content needle description)
    string(FIND "${content}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Gate 8 source contract failed: ${description}")
    endif()
endfunction()

function(reject_text content needle description)
    string(FIND "${content}" "${needle}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Gate 8 source contract failed: ${description}")
    endif()
endfunction()

read_required("EngineBridge/include/renegade/bridge/LightmapBakeService.h" gate8_header)
read_required("EngineBridge/src/LightmapBakeService.cpp" gate8_service)
read_required("EngineBridge/Phase5Gate8.cmake" gate8_bridge_cmake)
read_required("Studio/src/Phase5Gate8LightmapBaking.cpp" gate8_studio)
read_required("Studio/src/Phase5Gate5RenderWorkspace.cpp" render_workspace)
read_required("Studio/src/StudioApplication.h" studio_header)
read_required("Studio/src/StudioApplication.cpp" studio_source)
read_required("EngineBridge/src/SceneDocumentService.cpp" scene_document)
read_required("EngineBridge/src/SceneService.cpp" scene_service)
read_required("Studio/Phase5Gate8.cmake" gate8_studio_cmake)
read_required("CMakeLists.txt" root_cmake)

require_text("${gate8_header}" "class LightmapBakeService" "Renegade-owned bake service is not declared")
require_text("${gate8_header}" "LightmapBakeSession" "bake session boundary is missing")
require_text("${gate8_service}" "SetLightmapRenderRequest(true)" "native Wicked lightmap render request is not used")
require_text("${gate8_service}" "SaveLightmap()" "native Wicked Stop & Save path is not used")
require_text("${gate8_service}" "ClearLightmap()" "native Wicked lightmap clear path is not used")
require_text("${gate8_service}" "lightmapTextureData" "native serialized lightmap data is not retained")
require_text("${gate8_service}" "vertex_atlas" "native Wicked atlas channel is not used")
require_text("${gate8_service}" "vertex_ao" "native Wicked Vertex AO storage is not used")
require_text("${gate8_service}" "xatlas::Create" "pinned xatlas generation is not isolated in the bake service")
require_text("${gate8_service}" "RecordExecuted" "completed bake/AO changes are not recorded in CommandService")
require_text("${gate8_service}" "HydratePersistedLightmaps" "serialized native lightmaps are not rehydrated")
require_text("${gate8_service}" "BC6H_UF16" "BC6H restore path is missing")
require_text("${gate8_service}" "R11G11B10_FLOAT" "uncompressed lightmap restore path is missing")
reject_text("${gate8_service}" "ObjectWindow" "stock Wicked ObjectWindow leaked into EngineBridge")

require_text("${gate8_bridge_cmake}" "WickedEngine/Editor/xatlas.cpp" "pinned xatlas implementation is not compiled")
reject_text("${gate8_bridge_cmake}" "ObjectWindow.cpp" "Gate 8 must not compile the stock Wicked ObjectWindow")
require_text("${gate8_studio_cmake}" "Phase5Gate8LightmapBaking.cpp" "dedicated Gate 8 Studio source is not compiled")

require_text("${studio_header}" "renegade/bridge/LightmapBakeService.h" "Studio does not include the Gate 8 service contract")
require_text("${studio_header}" "CreateGate8BakeControls" "Gate 8 Studio declarations are missing")
require_text("${studio_header}" "LightmapBakeSession lightmapBakeSession_" "Studio does not own one bounded bake session")
require_text("${render_workspace}" "CreateGate8BakeControls();" "Gate 8 controls are not attached before the RENDER window is hidden")
require_text("${render_workspace}" "LayoutGate8BakeControls(fieldWidth, y);" "Gate 8 controls are not part of RENDER layout")
require_text("${render_workspace}" "RefreshGate8BakeControls();" "Gate 8 controls are not refreshed with the RENDER workspace")
require_text("${studio_source}" "TickGate8BakeControls();" "progress/status is not updated from the Studio frame loop")
require_text("${gate8_studio}" "Entity_IsDescendant(entity, selected)" "selected model roots do not expand to render descendants")
require_text("${render_workspace}" "CancelGate8Bake();" "leaving RENDER does not fail closed on an active bake")

require_text("${gate8_studio}" "START BAKE" "creator Start Bake control is missing")
require_text("${gate8_studio}" "STOP & SAVE" "creator Stop & Save control is missing")
require_text("${gate8_studio}" "CLEAR LIGHTMAP" "creator Clear Lightmap control is missing")
require_text("${gate8_studio}" "COMPUTE VERTEX AO" "creator Vertex AO compute control is missing")
require_text("${gate8_studio}" "renderLightmapPreview_.SetImage" "native lightmap preview is missing")
reject_text("${gate8_studio}" "ObjectWindow" "stock Wicked ObjectWindow UI is referenced by Renegade Studio")

require_text("${root_cmake}" "include(EngineBridge/Phase5Gate8.cmake)" "Gate 8 EngineBridge CMake integration is missing")
require_text("${root_cmake}" "include(Studio/Phase5Gate8.cmake)" "Gate 8 Studio CMake integration is missing")
require_text("${root_cmake}" "include(Tests/Phase5Gate8.cmake)" "Gate 8 tests are not included")
require_text("${scene_document}" "HydratePersistedLightmaps" "Studio prepared-scene adoption does not hydrate baked lightmaps")
require_text("${scene_service}" "HydratePersistedLightmaps" "Runtime SceneService load does not hydrate baked lightmaps")

if(EXISTS "${RENEGADE_SOURCE_DIR}/.github/workflows/phase5-gate8-integrate.yml")
    message(FATAL_ERROR "Gate 8 temporary integration workflow did not self-clean")
endif()

message(STATUS "Phase 5 Gate 8 source contract passed")
