cmake_minimum_required(VERSION 3.19)

function(read_required relative out_var)
    set(path "${RENEGADE_SOURCE_DIR}/${relative}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Gate 9 required source is missing: ${relative}")
    endif()
    file(READ "${path}" content)
    set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(require_text content needle description)
    string(FIND "${content}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Gate 9 source contract failed: ${description}")
    endif()
endfunction()

function(reject_text content needle description)
    string(FIND "${content}" "${needle}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Gate 9 source contract failed: ${description}")
    endif()
endfunction()

read_required("Studio/src/Phase5Gate9RenderDiagnostics.cpp" gate9_studio)
read_required("Studio/src/Phase5Gate5RenderWorkspace.cpp" render_workspace)
read_required("Studio/Phase5Gate9.cmake" gate9_cmake)
read_required("EngineBridge/include/renegade/bridge/RenderSettingsService.h" render_settings)
read_required("CMakeLists.txt" root_cmake)

require_text("${gate9_studio}" "WIREFRAME OVERLAY" "wireframe overlay creator mode is missing")
require_text("${gate9_studio}" "WIREFRAME ONLY" "wireframe-only creator mode is missing")
require_text("${gate9_studio}" "SetWireframeMode" "native Wicked wireframe state is not used")
require_text("${gate9_studio}" "SetDisableAlbedoMaps" "no-albedo diagnostic is not mapped to Wicked")
require_text("${gate9_studio}" "SetForceDiffuseLighting" "diffuse-only diagnostic is not mapped to Wicked")
require_text("${gate9_studio}" "SetForceUnlit" "unlit diagnostic is not mapped to Wicked")
require_text("${gate9_studio}" "SetToDrawDebugEnvProbes" "environment-probe visualizer mapping is missing")
require_text("${gate9_studio}" "SetToDrawDebugCameras" "camera/frustum visualizer mapping is missing")
require_text("${gate9_studio}" "SetToDrawDebugPartitionTree" "spatial-partition visualizer mapping is missing")
require_text("${gate9_studio}" "SetRaytraceDebugBVHVisualizerEnabled" "raytrace BVH visualizer mapping is missing")
require_text("${gate9_studio}" "SetFreezeCullingCameraEnabled" "freeze-culling diagnostic mapping is missing")
require_text("${gate9_studio}" "SetDebugLightCulling" "light-culling heatmap mapping is missing")
require_text("${gate9_studio}" "SetTemporalAADebugEnabled" "TAA diagnostic mapping is missing")
require_text("${gate9_studio}" "SURFEL_DEBUG_INCONSISTENCY" "exact pinned Surfel debug modes are incomplete")
require_text("${gate9_studio}" "SetSurfelGIDebugEnabled" "Surfel debug selector is not mapped to Wicked")
require_text("${gate9_studio}" "wi::profiler::DrawData" "native CPU/GPU profiler data is not drawn")
require_text("${gate9_studio}" "wi::profiler::SetEnabled" "native profiler enable/reset path is missing")
require_text("${gate9_studio}" "CPU/GPU profiler overlay" "creator profiler control is missing")
require_text("${gate9_studio}" "projectIdentity" "project-switch fail-closed tracking is missing")
require_text("${gate9_studio}" "sceneIdentity" "scene-switch fail-closed tracking is missing")
require_text("${gate9_studio}" "RESET DIAGNOSTICS" "one-shot diagnostics reset is missing")
require_text("${gate9_studio}" "ResetNativeDiagnostics" "bounded native reset path is missing")

require_text("${render_workspace}" "CreateGate9DiagnosticsControls();" "Gate 9 controls are not attached before RENDER is hidden")
require_text("${render_workspace}" "LayoutGate9DiagnosticsControls(fieldWidth, y);" "Gate 9 controls are not part of RENDER layout")
require_text("${render_workspace}" "RefreshGate9DiagnosticsControls();" "Gate 9 live state is not refreshed")
require_text("${render_workspace}" "ResetGate9Diagnostics();" "leaving RENDER does not clear diagnostics")
require_text("${gate9_cmake}" "Phase5Gate9RenderDiagnostics.cpp" "dedicated Gate 9 Studio source is not compiled")

require_text("${render_settings}" "RenderSettingsSchemaVersion = 3" "Gate 9 must not bump the accepted render-settings schema")
reject_text("${gate9_studio}" "RenderSettingsState" "Gate 9 transient state must not become persisted RenderSettingsState")
reject_text("${gate9_studio}" "SetEditorPreference" "Gate 9 diagnostic state must not persist as an editor preference")
reject_text("${gate9_studio}" "ProfilerWindow" "stock Wicked ProfilerWindow must not be integrated")
reject_text("${gate9_studio}" "GraphicsWindow" "stock Wicked GraphicsWindow must not be integrated")
reject_text("${gate9_studio}" "SetToDrawGridHelper" "stock Wicked grid helper must not be exposed by Gate 9")
reject_text("${gate9_studio}" "diagnostics_->active = true" "Gate 9 must not re-enable Wicked InfoDisplayer over Renegade chrome")

require_text("${root_cmake}" "include(Studio/Phase5Gate9.cmake)" "Gate 9 Studio integration is missing")
require_text("${root_cmake}" "include(Tests/Phase5Gate9.cmake)" "Gate 9 regression contract is not included")
require_text("${root_cmake}" "include(Tests/Phase5Gate8.cmake)" "Gate 8 regression contract was dropped")
require_text("${root_cmake}" "include(Tests/Phase5Gate7.cmake)" "Gate 7 regression contract was dropped")
require_text("${root_cmake}" "include(Tests/Phase5Gate6.cmake)" "Gate 6 regression contract was dropped")
require_text("${root_cmake}" "include(Tests/Phase5Gate5.cmake)" "Gate 5 regression contract was dropped")

message(STATUS "Phase 5 Gate 9 source contract passed")
