if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(SERVICE_HEADER "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/SceneComponentService.h")
set(SERVICE_SOURCE "${RENEGADE_SOURCE_DIR}/EngineBridge/src/SceneComponentService.cpp")
set(STUDIO_HEADER "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.h")
set(STUDIO_SOURCE "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.cpp")
set(TEST_SOURCE "${RENEGADE_SOURCE_DIR}/Tests/Phase5Gate1SceneComponentTests.cpp")

foreach(path IN ITEMS "${SERVICE_HEADER}" "${SERVICE_SOURCE}" "${STUDIO_HEADER}" "${STUDIO_SOURCE}" "${TEST_SOURCE}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 5 Gate 1 source contract input missing: ${path}")
    endif()
endforeach()

file(READ "${SERVICE_HEADER}" service_header)
file(READ "${SERVICE_SOURCE}" service_source)
file(READ "${STUDIO_HEADER}" studio_header)
file(READ "${STUDIO_SOURCE}" studio_source)
file(READ "${TEST_SOURCE}" test_source)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Phase 5 Gate 1 contract missing ${description}: ${needle}")
    endif()
endfunction()

require_text(service_header "ResolveSceneComponentAuthoringRoot" "reusable-root scene authoring resolver")
require_text(service_header "SetSceneNameCommand" "undoable creator name command")
require_text(service_header "SetSceneLayerMaskCommand" "undoable full layer-mask command")
require_text(service_header "SetSceneLayerBitCommand" "bit-preserving layer command")
require_text(service_header "SetMetadataPresetCommand" "undoable Metadata preset command")
require_text(service_header "SetObjectParticipationCommand" "undoable Object participation command")
require_text(service_source "ReusableAssetInstanceIdMetadataKey" "stable reusable-root detection")
require_text(service_source "scene.Entity_IsDescendant(entity, root)" "descendant whole-asset targeting")
require_text(service_source "scene_->layers.Remove(target.entity);" "Undo removal of Gate-created LayerComponent")
require_text(service_source "target.hadLayer ? target.mask : ~0u" "bit edit preserving each target mask")
require_text(service_source "object.SetNotVisibleInMainCamera(!value);" "native main-camera visibility mapping")
require_text(service_source "object.SetNotVisibleInReflections(!value);" "native reflection visibility mapping")

require_text(studio_header "std::array<SceneInspectorCheckBox, 32> sceneLayerBits_;" "32-bit layer UI")
require_text(studio_source "sceneLayerAllButton_.SetText(\"ALL\")" "layer ALL action")
require_text(studio_source "sceneLayerNoneButton_.SetText(\"NONE\")" "layer NONE action")
require_text(studio_source "checkbox.Create(std::to_string(bit));" "compact numbered 0-31 layer labels")
string(FIND "${studio_source}" "Scene Layer Bit " leaked_layer_label)
if(NOT leaked_layer_label EQUAL -1)
    message(FATAL_ERROR "Phase 5 Gate 1 contract forbids long internal layer labels in the compact grid")
endif()
require_text(studio_source "MetadataComponent::Preset::PointOfInterest" "complete native Metadata preset list")
require_text(studio_source "std::make_unique<bridge::SetSceneNameCommand>" "Inspector rename through CommandService")
require_text(studio_source "std::make_unique<bridge::SetSceneLayerBitCommand>" "Inspector layer-bit edit through CommandService")
require_text(studio_source "std::make_unique<bridge::SetSceneLayerMaskCommand>" "Inspector ALL/NONE through CommandService")
require_text(studio_source "std::make_unique<bridge::SetMetadataPresetCommand>" "Inspector Metadata through CommandService")
require_text(studio_source "std::make_unique<bridge::SetObjectParticipationCommand>" "Inspector Object flags through CommandService")
require_text(studio_source "OBJECT // MIXED // WHOLE-ASSET EDIT" "mixed reusable-object state presentation")
require_text(test_source "layer-bit edit destroyed unrelated bits on existing child" "mixed layer bit-preservation regression")
require_text(test_source "object participation Undo did not restore mixed prior state" "mixed Object Undo regression")
require_text(test_source "metadata Undo destroyed reusable asset identity" "Metadata identity preservation regression")

message(STATUS "Phase 5 Gate 1 source contract passed")
