if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_file path label)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 7B missing ${label}: ${path}")
    endif()
endfunction()

function(require_text text needle label)
    string(FIND "${text}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Phase 7B source contract missing ${label}: ${needle}")
    endif()
endfunction()

set(service_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/HumanoidRetargetService.h")
set(service_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/HumanoidRetargetService.cpp")
set(inspector_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7BHumanoidRetargetInspector.h")
set(inspector_source "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7BHumanoidRetargetInspector.cpp")
set(animation_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7AAnimationInspector.h")

require_file("${service_header}" "HumanoidRetargetService header")
require_file("${service_source}" "HumanoidRetargetService source")
require_file("${inspector_header}" "humanoid retarget inspector header")
require_file("${inspector_source}" "humanoid retarget inspector source")

file(READ "${service_source}" service)
file(READ "${inspector_source}" inspector)
file(READ "${animation_header}" animation)

require_text("${service}" "scene_->RetargetAnimation(" "native Wicked retarget call")
require_text("${service}" "destinationHumanoid_, sourceAnimation, true, &sourceScene" "baked native retarget")
require_text("${service}" "scene_->ResetPose(destinationHumanoid_)" "native pose reset")
require_text("${service}" "ImportModel_FBX(sourcePath_, sourceScene)" "native FBX converter")
require_text("${service}" "ImportModel_GLTF(sourcePath_, sourceScene)" "native GLTF/VRM converter")
require_text("${service}" "\".vrm\"" "VRM source classification")
require_text("${service}" "\".vrma\"" "VRMA source classification")
require_text("${service}" "SetHumanoidMappingCommand" "command-backed humanoid mapping")
require_text("${service}" "SetHumanoidBoneCommand" "command-backed manual correction")

require_text("${inspector}" "AUTO-MAP" "creator auto-map control")
require_text("${inspector}" "RESET POSE" "creator reset-pose control")
require_text("${inspector}" "IMPORT + RETARGET" "creator retarget control")
require_text("${inspector}" "RecordExecuted(std::move(command))" "retarget undo transaction")
require_text("${inspector}" "WISCENE / FBX / GLTF / GLB / VRM / VRMA" "all audited animation source formats")
require_text("${inspector}" "Phase7AnimationSectionId" "7A playback integration")
require_text("${animation}" "RegisterPhase7Gate7BHumanoidRetargetInspector" "7B inspector registration")
require_text("${animation}" "PreparePhase7Gate7BHumanoidRetargetInspector" "7B inspector layout preparation")

string(FIND "${inspector}" "HumanoidWindow.h" stock_humanoid_window)
if(NOT stock_humanoid_window EQUAL -1)
    message(FATAL_ERROR "Phase 7B must not embed Wicked's stock HumanoidWindow")
endif()

message(STATUS "Phase 7B native humanoid/retarget source contract passed")
