if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(require_file path label)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 7C missing ${label}: ${path}")
    endif()
endfunction()

function(require_text text needle label)
    string(FIND "${text}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Phase 7C source contract missing ${label}: ${needle}")
    endif()
endfunction()

set(service_header "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CharacterAnimationControlService.h")
set(service_source "${RENEGADE_SOURCE_DIR}/EngineBridge/src/CharacterAnimationControlService.cpp")
set(inspector_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7CCharacterControlsInspector.h")
set(inspector_source "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7CCharacterControlsInspector.cpp")
set(animation_header "${RENEGADE_SOURCE_DIR}/Studio/src/Phase7Gate7AAnimationInspector.h")
set(root_cmake "${RENEGADE_SOURCE_DIR}/CMakeLists.txt")

require_file("${service_header}" "CharacterAnimationControlService header")
require_file("${service_source}" "CharacterAnimationControlService source")
require_file("${inspector_header}" "character controls inspector header")
require_file("${inspector_source}" "character controls inspector source")

file(READ "${service_source}" service)
file(READ "${inspector_source}" inspector)
file(READ "${animation_header}" animation)
file(READ "${root_cmake}" root)

require_text("${service}" "scene_->inverse_kinematics" "native IK component storage")
require_text("${service}" "ik->SetDisabled(state.disabled)" "native IK enable state")
require_text("${service}" "humanoid->SetLookAtEnabled(state.enabled)" "native humanoid look-at")
require_text("${service}" "expressions->SetForceTalkingEnabled(state.forceTalking)" "native talking automation")
require_text("${service}" "expression.SetBinary(state.binary)" "native binary expressions")
require_text("${service}" "expression.SetDirty()" "native expression dirty propagation")
require_text("${service}" "SetInverseKinematicsStateCommand" "command-backed IK edits")
require_text("${service}" "SetHumanoidLookAtStateCommand" "command-backed look-at edits")
require_text("${service}" "SetExpressionMasterStateCommand" "command-backed expression automation")
require_text("${service}" "SetExpressionEntryStateCommand" "command-backed expression weights")

require_text("${inspector}" "ADD IK" "creator IK authoring")
require_text("${inspector}" "LOOK-AT // native humanoid head + eye solver" "creator look-at surface")
require_text("${inspector}" "BLINKS / SEC" "creator blink controls")
require_text("${inspector}" "Force Talking" "creator talking control")
require_text("${inspector}" "Expression Weight" "creator expression weight control")
require_text("${inspector}" "ExpressionOverride::Blend" "expression override controls")
require_text("${inspector}" "OnValueCommitted" "committed slider authoring")
require_text("${animation}" "RegisterPhase7Gate7CCharacterControlsInspector" "7C inspector registration")
require_text("${animation}" "PreparePhase7Gate7CCharacterControlsInspector" "7C inspector layout preparation")
require_text("${root}" "Phase7Gate7CCharacterControlsInspector.cpp" "7C Studio target ownership")
require_text("${root}" "include(Tests/Phase7Gate7C.cmake)" "7C test registration")

foreach(stock_header IN ITEMS "IKWindow.h" "HumanoidWindow.h" "ExpressionWindow.h")
    string(FIND "${inspector}" "${stock_header}" stock_window)
    if(NOT stock_window EQUAL -1)
        message(FATAL_ERROR "Phase 7C must not embed Wicked stock editor window: ${stock_header}")
    endif()
endforeach()

message(STATUS "Phase 7C native IK/look-at/expression source contract passed")
