if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(SERVICE_HEADER "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/CameraService.h")
set(SERVICE_SOURCE "${RENEGADE_SOURCE_DIR}/EngineBridge/src/CameraService.cpp")
set(STUDIO_HEADER "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.h")
set(STUDIO_SOURCE "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.cpp")
set(CHROME_HEADER "${RENEGADE_SOURCE_DIR}/Studio/src/RenegadeStudioChrome.h")
set(CHROME_SOURCE "${RENEGADE_SOURCE_DIR}/Studio/src/RenegadeStudioChrome.cpp")
set(TEST_SOURCE "${RENEGADE_SOURCE_DIR}/Tests/Phase5Gate2CameraTests.cpp")

foreach(path IN ITEMS "${SERVICE_HEADER}" "${SERVICE_SOURCE}" "${STUDIO_HEADER}" "${STUDIO_SOURCE}" "${CHROME_HEADER}" "${CHROME_SOURCE}" "${TEST_SOURCE}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 5 Gate 2 source contract input missing: ${path}")
    endif()
endforeach()

file(READ "${SERVICE_HEADER}" service_header)
file(READ "${SERVICE_SOURCE}" service_source)
file(READ "${STUDIO_HEADER}" studio_header)
file(READ "${STUDIO_SOURCE}" studio_source)
file(READ "${CHROME_HEADER}" chrome_header)
file(READ "${CHROME_SOURCE}" chrome_source)
file(READ "${TEST_SOURCE}" test_source)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Phase 5 Gate 2 contract missing ${description}: ${needle}")
    endif()
endfunction()

require_text(service_header "struct CameraState" "camera state bridge")
require_text(service_header "CreateCameraCommand" "undoable camera creation")
require_text(service_header "SetCameraCommand" "undoable camera property editing")
require_text(service_source "scene_->Entity_CreateCamera" "native Wicked camera creation")
require_text(service_source "camera.SetOrtho" "native orthographic projection")
require_text(service_source "camera.focal_length" "native depth-of-field focus distance")
require_text(service_source "camera.aperture_size" "native aperture strength")
require_text(service_source "camera.ortho_vertical_size" "native orthographic size")
require_text(service_source "camera.UpdateCamera()" "camera matrix refresh")

require_text(chrome_header "CreateCamera" "ADD menu camera action")
require_text(chrome_source "{\"CAMERA\", true}" "creator-facing ADD CAMERA item")
require_text(studio_header "CameraService.h" "Studio camera bridge include")
require_text(studio_header "CameraField" "camera slider field routing")
require_text(studio_source "std::make_unique<bridge::CreateCameraCommand>" "create-from-view through CommandService")
require_text(studio_source "std::make_unique<bridge::SetCameraCommand>" "camera Inspector through CommandService")
require_text(studio_source "std::make_unique<bridge::SetTransformCommand>" "align camera to editor view through central transform command")
require_text(studio_source "VIEW FROM CAMERA" "camera preview action")
require_text(studio_source "ALIGN CAMERA TO VIEW" "camera alignment action")
require_text(studio_source "camera->GetInvView()" "create/align from current editor view")
require_text(studio_source "bridge::ApplyCamera(*camera" "editor view adopts selected scene camera projection")
require_text(test_source "camera property Undo did not restore prior state" "camera property Undo regression")
require_text(test_source "camera create Redo did not restore the same camera entity" "camera creation history regression")

message(STATUS "Phase 5 Gate 2 source contract passed")
