if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

set(SERVICE_HEADER "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/RenderSettingsService.h")
set(SERVICE_SOURCE "${RENEGADE_SOURCE_DIR}/EngineBridge/src/RenderSettingsService.cpp")
set(STUDIO_HEADER "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.h")
set(STUDIO_RENDER "${RENEGADE_SOURCE_DIR}/Studio/src/Phase5Gate5RenderWorkspace.cpp")
set(RUNTIME_SOURCE "${RENEGADE_SOURCE_DIR}/Runtime/src/RuntimeApplication.cpp")
set(TEST_SOURCE "${RENEGADE_SOURCE_DIR}/Tests/Phase5Gate6RenderSettingsTests.cpp")
set(CONTRACT_DOC "${RENEGADE_SOURCE_DIR}/docs/PHASE5_GATE6_AO_GI_REFLECTIONS.md")

foreach(path IN ITEMS
    "${SERVICE_HEADER}" "${SERVICE_SOURCE}" "${STUDIO_HEADER}"
    "${STUDIO_RENDER}" "${RUNTIME_SOURCE}" "${TEST_SOURCE}" "${CONTRACT_DOC}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Phase 5 Gate 6 source contract input missing: ${path}")
    endif()
endforeach()

file(READ "${SERVICE_HEADER}" service_header)
file(READ "${SERVICE_SOURCE}" service_source)
file(READ "${STUDIO_HEADER}" studio_header)
file(READ "${STUDIO_RENDER}" studio_render)
file(READ "${RUNTIME_SOURCE}" runtime_source)
file(READ "${TEST_SOURCE}" test_source)
file(READ "${CONTRACT_DOC}" contract_doc)

function(require_text haystack needle description)
    string(FIND "${${haystack}}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Phase 5 Gate 6 contract missing ${description}: ${needle}")
    endif()
endfunction()

require_text(service_header "RenderSettingsSchemaVersion = 2" "schema-v2 render settings")
require_text(service_header "enum class RenderAmbientOcclusion" "curated AO enum")
require_text(service_header "enum class RenderQuality" "curated render quality enum")
require_text(service_header "ambientOcclusionPower" "AO power state")
require_text(service_header "ssgiDepthRejection" "SSGI depth rejection state")
require_text(service_header "giBoost" "GI boost state")
require_text(service_header "planarReflectionResolutionScale" "planar reflection quality state")
require_text(service_header "ssrQuality" "SSR quality state")
require_text(service_header "reflectionRoughnessCutoff" "reflection roughness state")

require_text(service_source "schema != 1 && schema != RenderSettingsSchemaVersion" "lossless schema-v1 migration")
require_text(service_source "path.setAO(" "native AO application")
require_text(service_source "path.setAOPower(" "native AO power application")
require_text(service_source "path.setAORange(" "native AO range application")
require_text(service_source "path.setAOSampleCount(" "native AO samples application")
require_text(service_source "path.setSSGIEnabled(" "native SSGI application")
require_text(service_source "path.setSSGIDepthRejection(" "native SSGI depth application")
require_text(service_source "wi::renderer::SetGIBoost(" "native GI boost application")
require_text(service_source "path.setReflectionsEnabled(" "native planar reflection toggle")
require_text(service_source "path.setPlanarReflectionQuality(" "native planar quality application")
require_text(service_source "path.setSSREnabled(" "native SSR application")
require_text(service_source "path.setSSRQuality(" "native SSR quality application")
require_text(service_source "path.setReflectionRoughnessCutoff(" "native reflection roughness application")

require_text(studio_render "AMBIENT OCCLUSION // NATIVE WICKED" "AO creator section")
require_text(studio_render "GLOBAL ILLUMINATION // SCREEN SPACE" "GI creator section")
require_text(studio_render "REFLECTIONS // SCREEN + PLANAR" "reflection creator section")
require_text(studio_render "RenderAmbientOcclusion::SSAO" "SSAO creator mode")
require_text(studio_render "RenderAmbientOcclusion::HBAO" "HBAO creator mode")
require_text(studio_render "RenderAmbientOcclusion::MSAO" "MSAO creator mode")
require_text(studio_render "RenderToggle::Ssgi" "SSGI creator toggle")
require_text(studio_render "RenderToggle::PlanarReflections" "planar reflection creator toggle")
require_text(studio_render "RenderToggle::Ssr" "SSR creator toggle")
require_text(studio_render "setSSGIDepthRejection" "direct SSGI slider preview")
require_text(studio_render "wi::renderer::SetGIBoost" "direct GI boost slider preview")
require_text(studio_render "setReflectionRoughnessCutoff" "direct reflection cutoff preview")

string(FIND "${studio_render}" "RenderAmbientOcclusion::RTAO" rtao_ui)
if(NOT rtao_ui EQUAL -1)
    message(FATAL_ERROR "Gate 6 must not expose RTAO; it belongs to Gate 7")
endif()

require_text(runtime_source "ApplyRenderSettingsToPath(" "shared Runtime render-settings application seam")
require_text(test_source "schema-v1 carrier did not migrate losslessly" "schema migration regression")
require_text(contract_doc "Ray-traced reflections remain Gate 7" "bounded Gate 7 deferral")

message(STATUS "Phase 5 Gate 6 source contract passed")
