if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(read_required relative output)
    set(path "${RENEGADE_SOURCE_DIR}/${relative}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "S4B source contract missing ${relative}")
    endif()
    file(READ "${path}" text)
    set(${output} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "S4B source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(NOT index EQUAL -1)
        message(FATAL_ERROR "S4B source contract forbids ${description}: ${needle}")
    endif()
endfunction()

read_required("CMakeLists.txt" root_cmake)
read_required("EngineBridge/include/renegade/bridge/ScriptAuthoringService.h" authoring_header)
read_required("EngineBridge/src/ScriptAuthoringService.cpp" authoring_source)
read_required("EngineBridge/include/renegade/bridge/StudioSession.h" studio_session)
read_required("Studio/src/S4BScriptAttachmentInspector.h" inspector_header)
read_required("Studio/src/S4BScriptAttachmentInspector.cpp" inspector_source)
read_required("Studio/src/S1BInspectorSectionMigration.cpp" registry_source)

require_text(root_cmake "include(EngineBridge/S4BScriptAuthoring.cmake)" "EngineBridge S4B build registration")
require_text(root_cmake "include(Studio/S4BScriptAttachmentInspector.cmake)" "Studio S4B build registration")
require_text(root_cmake "include(Tests/S4BScriptAuthoring.cmake)" "S4B acceptance test registration")

require_text(authoring_source "EvaluateScriptMetadata" "restricted S4A metadata discovery")
require_text(authoring_source "ApplyScriptMetadataDefaults" "metadata defaults bridge into S2 properties")
require_text(authoring_source "MakeAddScriptAttachmentCommand" "S2 attach Undo/Redo command")
require_text(authoring_source "MakeRemoveScriptAttachmentCommand" "S2 remove Undo/Redo command")
require_text(authoring_source "MakeSetScriptEnabledCommand" "S2 enabled Undo/Redo command")
require_text(authoring_source "MakeMoveScriptAttachmentCommand" "S2 reorder Undo/Redo command")
require_text(authoring_source "GLOBAL SCRIPT authoring is deferred to S4D." "S4D scope boundary")
require_text(authoring_source "WriteScriptDocument" "transactional scripting companion persistence")
require_text(authoring_source "ValidateScriptDocumentAgainstScene" "Scene identity validation before persistence")

require_text(studio_session "ScriptAuthoringService scripts_" "StudioSession scripting authority")
require_text(studio_session "scripts_.SaveForScene" "Scene save companion handoff")
require_text(studio_session "commands_.MarkUnsaved()" "failed companion save dirty-state recovery")
require_text(studio_session "scripts_.Invalidate()" "Scene/project replacement scripting invalidation")

require_text(inspector_header "S4BActionSectionId = \"action\"" "ACTION Inspector section ID")
require_text(inspector_header "S4BScriptSectionId = \"script\"" "SCRIPT Inspector section ID")
require_text(inspector_source "descriptor.defaultExpanded = false" "collapsed-by-default scripting sections")
require_text(inspector_source "RegisterS4BScriptAttachmentInspector" "S4B provider registration seam")
require_text(inspector_source "PrepareS4BScriptAttachmentInspector" "stale scripting-widget reset seam")
require_text(inspector_source "ScriptPresentation::Action" "ACTION creator role")
require_text(inspector_source "ScriptPresentation::Script" "SCRIPT creator role")
require_text(inspector_source "attachments[neighbour]->order" "absolute S2 order mapping for role-local UP/DOWN")
require_text(registry_source "RegisterS4BScriptAttachmentInspector" "S1 provider-registry integration")
require_text(registry_source "PrepareS4BScriptAttachmentInspector" "S1 layout reset integration")

forbid_text(authoring_source "ScriptComponent" "Wicked ScriptComponent creator authority")
forbid_text(authoring_source "native_id" "raw native entity IDs")
forbid_text(authoring_source "wi::lua::" "Wicked global Lua VM")
forbid_text(inspector_source "ScriptComponent" "Studio ScriptComponent coupling")
forbid_text(inspector_source "native_id" "Studio raw native entity IDs")

message(STATUS "S4B script authoring source contract passed")
