if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(read_required relative output)
    set(path "${RENEGADE_SOURCE_DIR}/${relative}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "S4C source contract missing ${relative}")
    endif()
    file(READ "${path}" text)
    set(${output} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "S4C source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(NOT index EQUAL -1)
        message(FATAL_ERROR "S4C source contract forbids ${description}: ${needle}")
    endif()
endfunction()

read_required("CMakeLists.txt" root_cmake)
read_required("EngineBridge/include/renegade/bridge/ScriptPropertyAuthoringService.h" property_header)
read_required("EngineBridge/src/ScriptPropertyAuthoringService.cpp" property_source)
read_required("Studio/src/S4CScriptPropertyControls.h" controls_header)
read_required("Studio/src/S4CScriptPropertyControls.cpp" controls_source)
read_required("Studio/src/S4BScriptAttachmentInspector.cpp" inspector_source)

require_text(root_cmake "include(EngineBridge/S4CScriptPropertyAuthoring.cmake)" "EngineBridge S4C build registration")
require_text(root_cmake "include(Studio/S4CScriptPropertyControls.cmake)" "Studio S4C build registration")
require_text(root_cmake "include(Tests/S4CScriptPropertyAuthoring.cmake)" "S4C acceptance test registration")

require_text(property_header "NormalizeScriptPropertyForAuthoring" "metadata-aware normalization seam")
require_text(property_header "CommitScriptPropertyAuthoringEdit" "Undo/Redo property commit seam")
require_text(property_source "MakeSetScriptPropertyCommand" "S2 property command authority")
require_text(property_source "commands.Execute" "shared CommandService history")
require_text(property_source "Reference-backed script properties are authored by S4D pickers." "S4D reference boundary")
require_text(property_source "metadata.hasMinimum" "numeric minimum enforcement")
require_text(property_source "metadata.hasMaximum" "numeric maximum enforcement")
require_text(property_source "metadata.hasStep" "numeric step enforcement")
require_text(property_source "metadata.enumOptions" "enum option enforcement")

require_text(controls_header "S4CScriptPropertyEditor" "generated property editor module")
require_text(controls_header "SceneInspectorCheckBox" "boolean control")
require_text(controls_header "SceneInspectorTextInputField" "numeric/string/vector component controls")
require_text(controls_header "SceneInspectorComboBox" "enum control")
require_text(controls_source "ScriptPropertyType::Colour" "colour component control")
require_text(controls_source "ScriptPropertyType::Vector2" "Vector2 component control")
require_text(controls_source "ScriptPropertyType::Vector3" "Vector3 component control")
require_text(controls_source "Unresolved — picker in S4D" "reference placeholder without raw IDs")
require_text(controls_source "CommitScriptPropertyAuthoringEdit" "UI to governed property commit handoff")

require_text(inspector_source "S4CScriptPropertyControls.h" "S4B attachment-row S4C integration")
require_text(inspector_source "S4CScriptPropertyEditor" "per-attachment generated property editor")
require_text(inspector_source "MeasureHeight()" "dynamic Inspector section height")

forbid_text(property_source "ScriptComponent" "Wicked ScriptComponent property authority")
forbid_text(property_source "wi::lua::" "Wicked global Lua VM")
forbid_text(controls_source "native_id" "raw native entity IDs")
forbid_text(controls_source "referenceId.c_str" "raw stable reference ID presentation")

message(STATUS "S4C typed script property authoring source contract passed")
