if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

function(read_required relative output)
    set(path "${RENEGADE_SOURCE_DIR}/${relative}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "S4D source contract missing ${relative}")
    endif()
    file(READ "${path}" text)
    set(${output} "${text}" PARENT_SCOPE)
endfunction()

function(require_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "S4D source contract missing ${description}: ${needle}")
    endif()
endfunction()

function(forbid_text text_var needle description)
    string(FIND "${${text_var}}" "${needle}" index)
    if(NOT index EQUAL -1)
        message(FATAL_ERROR "S4D source contract forbids ${description}: ${needle}")
    endif()
endfunction()

read_required("CMakeLists.txt" root_cmake)
read_required("EngineBridge/include/renegade/bridge/ScriptReferenceAuthoringService.h" reference_header)
read_required("EngineBridge/src/ScriptReferenceAuthoringService.cpp" reference_source)
read_required("EngineBridge/include/renegade/bridge/ScriptAuthoringService.h" authoring_header)
read_required("EngineBridge/src/ScriptAuthoringService.cpp" authoring_source)
read_required("Studio/src/S4CScriptPropertyControls.h" property_header)
read_required("Studio/src/S4CScriptPropertyControls.cpp" property_source)
read_required("Studio/src/S4DGlobalScriptInspector.h" global_header)
read_required("Studio/src/S4DGlobalScriptInspector.cpp" global_source)
read_required("Studio/src/S1BInspectorSectionMigration.cpp" registry_source)
read_required("Runtime/src/RuntimeScriptRuntime.cpp" runtime_source)

require_text(root_cmake "include(EngineBridge/S4DScriptReferenceAuthoring.cmake)" "S4D EngineBridge build registration")
require_text(root_cmake "include(Studio/S4DGlobalScriptInspector.cmake)" "S4D Studio build registration")
require_text(root_cmake "include(Tests/S4DScriptReferenceAuthoring.cmake)" "S4D acceptance registration")

require_text(reference_header "ScriptReferenceOption" "governed reference option model")
require_text(reference_header "CommitScriptReferenceAuthoringEdit" "reference command seam")
require_text(reference_source "PersistentEntityId" "persistent Scene reference identity")
require_text(reference_source "scene.animations" "animation entity reference enumeration")
require_text(reference_source "ReadAssetRegistry" "LC01 asset identity authority")
require_text(reference_source "AssetType::Audio" "audio asset filtering")
require_text(reference_source "MakeSetScriptPropertyCommand" "S2 reference property command")
require_text(reference_source "commands.Execute" "shared reference Undo/Redo history")
require_text(reference_source "unresolved reference can be preserved" "unresolved reference preservation policy")

require_text(authoring_header "LevelAttachments" "Level attachment query")
require_text(authoring_header "AttachLevelSource" "Level attachment command seam")
require_text(authoring_source "ScriptScope::Level" "GLOBAL SCRIPT Level scope")
require_text(authoring_source "Only GLOBAL SCRIPT sources can be attached at Level scope." "GLOBAL SCRIPT role guard")
require_text(authoring_source "ApplyScriptMetadataDefaults" "GLOBAL metadata defaults")
require_text(authoring_source "MakeAddScriptAttachmentCommand" "GLOBAL add command authority")
forbid_text(authoring_source "GLOBAL SCRIPT authoring is deferred to S4D." "obsolete GLOBAL SCRIPT rejection")

require_text(property_header "SceneInspectorComboBox referenceValue" "reference picker control")
require_text(property_header "std::vector<bridge::ScriptReferenceOption> referenceOptions" "picker option state")
require_text(property_source "EnumerateScriptReferenceOptions" "picker discovery handoff")
require_text(property_source "CommitScriptReferenceAuthoringEdit" "picker command handoff")
require_text(property_source "⚠ Unresolved" "visible unresolved repair state")
require_text(property_source "(None)" "explicit reference clear choice")
forbid_text(property_source "SetText(row.value.referenceId" "raw stable ID presentation")
forbid_text(property_source "referenceId.c_str" "raw stable ID presentation")

require_text(global_header "S4DGlobalScriptSectionId = \"global-script\"" "GLOBAL SCRIPT section identity")
require_text(global_source "descriptor.defaultExpanded = false" "collapsed GLOBAL SCRIPT section")
require_text(global_source "ScriptPresentation::GlobalScript" "GLOBAL SCRIPT role")
require_text(global_source "LevelAttachments" "GLOBAL SCRIPT Level query")
require_text(global_source "AttachLevelSource" "GLOBAL SCRIPT attach command")
require_text(global_source "S4CScriptPropertyEditor" "typed GLOBAL SCRIPT property editor")
require_text(global_source "MoveAttachment" "GLOBAL SCRIPT ordering")
require_text(global_source "SetAttachmentEnabled" "GLOBAL SCRIPT enabled state")
require_text(global_source "RemoveAttachment" "GLOBAL SCRIPT removal")

require_text(registry_source "RegisterS4DGlobalScriptInspector" "shared Inspector registration")
require_text(registry_source "PrepareS4DGlobalScriptInspector" "stale GLOBAL widget reset")
require_text(registry_source "S4DGlobalScriptSectionId" "shared disclosure policy")

# S3 already consumes Level attachments in deterministic runtime order. S4D
# must close authoring without introducing a second execution path.
require_text(runtime_source "ScriptScope::Level" "existing governed Level runtime support")

foreach(text_var reference_source property_source global_source)
    forbid_text(${text_var} "ScriptComponent" "Wicked ScriptComponent authority")
    forbid_text(${text_var} "native_id" "raw native entity IDs")
    forbid_text(${text_var} "wi::lua::" "Wicked global Lua VM")
endforeach()

message(STATUS "S4D references, GLOBAL SCRIPT and hardening source contract passed")
