if(NOT DEFINED RENEGADE_SOURCE_DIR)
 message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/GameplayEventService.h" h)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/GameplayEventService.cpp" c)
foreach(n IN ITEMS "MaxEvents" "MaxPayloadLength" "TryDequeue" "DroppedCount")
 string(FIND "${h}" "${n}" i)
 if(i EQUAL -1)
 message(FATAL_ERROR "S5C contract missing ${n}")
endif()
endforeach()
string(FIND "${c}" "queue is full" i)
if(i EQUAL -1)
 message(FATAL_ERROR "S5C overflow rejection missing")
endif()
message(STATUS "S5C gameplay event source contract passed")
