if(NOT DEFINED RENEGADE_SOURCE_DIR)
    message(FATAL_ERROR "RENEGADE_SOURCE_DIR is required")
endif()

file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/VegetationService.cpp" WD01_SERVICE)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/WD01Vegetation.cpp" WD01_STUDIO)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/CMakeLists.txt" WD01_STUDIO_CMAKE)
file(READ "${RENEGADE_SOURCE_DIR}/Runtime/CMakeLists.txt" WD01_RUNTIME_CMAKE)

function(wd01_require CONTENT NEEDLE MESSAGE_TEXT)
    string(FIND "${CONTENT}" "${NEEDLE}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "WD01 contract: ${MESSAGE_TEXT}")
    endif()
endfunction()

wd01_require("${WD01_SERVICE}" "preset.hairs[0]" "must source the pinned Wicked HairParticleSystem")
wd01_require("${WD01_SERVICE}" "chunk.grass.vertex_lengths[index] = target" "must persist native per-chunk masks")
wd01_require("${WD01_SERVICE}" "wi::HairParticleSystem::REBUILD_BUFFERS" "must use Wicked's native buffer rebuild path")
wd01_require("${WD01_SERVICE}" "mesh->aabb.transform(world)" "must broad-phase against transformed chunk mesh bounds")
wd01_require("${WD01_SERVICE}" "FinalizeWickedVegetationStroke" "must defer distribution finalization to completed strokes")
wd01_require("${WD01_SERVICE}" "ManualChunkKey" "must distinguish newly generated chunks from painted chunks")
wd01_require("${WD01_STUDIO}" "FILTER_TERRAIN" "viewport brush must pick native terrain")
wd01_require("${WD01_STUDIO}" "PaintWickedVegetation" "Studio must delegate painting through EngineBridge")
wd01_require("${WD01_STUDIO}" "WickedVegetationStrokeCommand" "completed strokes must be Undo/Redo commands")
wd01_require("${WD01_STUDIO}" "VEGETATION // WICKED GRASS" "grass UI must live in Renegade's Terrain inspector")
wd01_require("${WD01_STUDIO_CMAKE}" "WickedEngine/Content/terrain/grass.wiscene" "Studio must package Wicked grass.wiscene")
wd01_require("${WD01_STUDIO_CMAKE}" "WickedEngine/Content/terrain/grassparticle.png" "Studio must package Wicked grass texture")
wd01_require("${WD01_RUNTIME_CMAKE}" "WickedEngine/Content/terrain/grass.wiscene" "Runtime must package Wicked grass.wiscene")
wd01_require("${WD01_RUNTIME_CMAKE}" "WickedEngine/Content/terrain/grassparticle.png" "Runtime must package Wicked grass texture")

string(FIND "${WD01_STUDIO}" "HairParticleWindow" STOCK_WINDOW)
if(NOT STOCK_WINDOW EQUAL -1)
    message(FATAL_ERROR "WD01 contract: stock Wicked Editor UI must not be embedded")
endif()
