file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/VegetationService.h" WD01_HEADER)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/src/VegetationService.cpp" WD01_SERVICE)
file(READ "${RENEGADE_SOURCE_DIR}/EngineBridge/include/renegade/bridge/VegetationAppearanceService.h" WD01_APPEARANCE)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/WD01Vegetation.cpp" WD01_STUDIO)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/src/StudioApplication.cpp" WD01_APP)
file(READ "${RENEGADE_SOURCE_DIR}/Studio/CMakeLists.txt" WD01_STUDIO_CMAKE)

function(wd01_require HAYSTACK NEEDLE MESSAGE_TEXT)
    string(FIND "${${HAYSTACK}}" "${NEEDLE}" FOUND)
    if(FOUND EQUAL -1)
        message(FATAL_ERROR "WD01 contract: ${MESSAGE_TEXT}")
    endif()
endfunction()

function(wd01_require_exact_count HAYSTACK NEEDLE EXPECTED MESSAGE_TEXT)
    set(REMAINING "${${HAYSTACK}}")
    set(COUNT 0)
    while(TRUE)
        string(FIND "${REMAINING}" "${NEEDLE}" FOUND)
        if(FOUND EQUAL -1)
            break()
        endif()
        math(EXPR COUNT "${COUNT} + 1")
        string(LENGTH "${NEEDLE}" NEEDLE_LENGTH)
        math(EXPR NEXT "${FOUND} + ${NEEDLE_LENGTH}")
        string(SUBSTRING "${REMAINING}" ${NEXT} -1 REMAINING)
    endwhile()
    if(NOT COUNT EQUAL EXPECTED)
        message(FATAL_ERROR "WD01 contract: ${MESSAGE_TEXT} (expected ${EXPECTED}, found ${COUNT})")
    endif()
endfunction()

wd01_require(WD01_HEADER "VegetationBrushMode" "missing Paint/Delete brush contract")
wd01_require(WD01_HEADER "VegetationStrokeCommand" "missing vegetation Undo/Redo command")
wd01_require(WD01_SERVICE "wi::scene::LoadModel(grassScene, grassScenePath)" "must consume native Wicked grass.wiscene")
wd01_require(WD01_SERVICE "vertex_lengths" "must author native Wicked hair vertex mask")
wd01_require(WD01_SERVICE "CreateFromMesh" "must use native Wicked hair distribution")
wd01_require(WD01_STUDIO "VEGETATION // GRASS" "missing Terrain vegetation section")
wd01_require(WD01_STUDIO "PAINT" "missing creator Paint tool")
wd01_require(WD01_STUDIO "DELETE" "missing creator Delete tool")
wd01_require(WD01_APP "HandleWd01Vegetation(pointer)" "viewport does not route vegetation brush")
wd01_require(WD01_STUDIO_CMAKE "WickedEngine/Content/terrain/grass.wiscene" "Studio does not package Wicked grass scene")
wd01_require(WD01_STUDIO_CMAKE "WickedEngine/Content/terrain/grassparticle.png" "Studio does not package Wicked grass texture")

# Owner-approved interactive paint baseline, accepted at 02d5b90c8e7faee011eebf679cb1f3a1df107d73.
# These checks intentionally protect the native live-mask update seam that fixed
# visible painting and eliminated flicker/re-randomisation while a stroke is active.
wd01_require(WD01_SERVICE "StableInactiveLength = 1.0f / 255.0f" "stable Wicked R8 mask threshold changed")
wd01_require(WD01_SERVICE "BuildStrokeSamples(beforeState, center, brushRadius)" "continuous stroke interpolation was removed")
wd01_require(WD01_SERVICE "if (texture.name == texturePath && texture.resource.IsValid())" "grass material rebind is no longer idempotent")
wd01_require(WD01_SERVICE "live->vertex_lengths = chunk.grass.vertex_lengths" "live grass mask is not updated in place")
wd01_require(WD01_SERVICE "live->_flags |= wi::HairParticleSystem::REBUILD_BUFFERS" "live grass no longer uses Wicked deferred rebuild path")
wd01_require_exact_count(WD01_SERVICE "*live = chunk.grass;" 1 "live HairParticle may only be wholesale-copied on first creation")
wd01_require_exact_count(WD01_SERVICE "live->CreateFromMesh(*mesh);" 1 "live CreateFromMesh may only occur on first creation")

# Appearance is additive over the locked paint backend. It may alter only native
# non-topology HairParticle properties and must never rebuild the emitter buffers.
wd01_require(WD01_APPEARANCE "VegetationAppearanceSettings" "missing isolated grass appearance settings contract")
wd01_require(WD01_APPEARANCE "hair.length = settings.length" "Length is not mapped to native Wicked hair")
wd01_require(WD01_APPEARANCE "hair.width = settings.width" "Width is not mapped to native Wicked hair")
wd01_require(WD01_APPEARANCE "hair.randomness = settings.randomness" "Randomness is not mapped to native Wicked hair")
wd01_require(WD01_APPEARANCE "hair.randomSeed = settings.randomSeed" "Random Seed is not mapped to native Wicked hair")
wd01_require(WD01_APPEARANCE "hair.uniformity = settings.uniformity" "Uniformity is not mapped to native Wicked hair")
wd01_require(WD01_STUDIO "APPEARANCE [-]" "missing collapsible Appearance section")
wd01_require(WD01_STUDIO "WD01 Grass Length" "missing grass Length control")
wd01_require(WD01_STUDIO "WD01 Grass Width" "missing grass Width control")
wd01_require(WD01_STUDIO "WD01 Grass Randomness" "missing grass Randomness control")
wd01_require(WD01_STUDIO "WD01 Grass Random Seed" "missing grass Random Seed control")
wd01_require(WD01_STUDIO "WD01 Grass Uniformity" "missing grass Uniformity control")
string(FIND "${WD01_APPEARANCE}" "REBUILD_BUFFERS" APPEARANCE_REBUILD)
if(NOT APPEARANCE_REBUILD EQUAL -1)
    message(FATAL_ERROR "WD01 contract: Appearance controls must not rebuild HairParticle emitter buffers")
endif()

# Terrain's pre-WD01 action rows are anchored at Y 726 and end at Y 834
# (save row at 806 with 28 px controls). Vegetation must append below that
# boundary so Wicked's normal Window scroll-range calculation can expose it
# without overlapping Undo/Redo/Save controls.
wd01_require(WD01_APP "? 726.0f" "Terrain action-row anchor changed; re-audit vegetation layout boundary")
wd01_require(WD01_STUDIO "TerrainInspectorActionsBottom = 834.0f" "missing audited Terrain action-row bottom boundary")
wd01_require(WD01_STUDIO "VegetationInspectorTop =" "missing vegetation scroll-extension anchor")
wd01_require(WD01_STUDIO "TerrainInspectorActionsBottom + VegetationInspectorGap" "vegetation must begin after existing Terrain action rows")
wd01_require(WD01_STUDIO "place(controls.sectionLabel, VegetationInspectorTop, 20.0f)" "vegetation section is not anchored below Terrain actions")
wd01_require(WD01_STUDIO "place(controls.status, VegetationInspectorTop + 148.0f, 34.0f)" "vegetation content does not extend the Terrain scroll range")
wd01_require(WD01_STUDIO "place(controls.appearanceHeader, VegetationInspectorTop + 190.0f)" "Appearance section is not appended below the accepted paint controls")

foreach(FORBIDDEN IN ITEMS "HairParticleWindow" "PaintToolWindow")
    string(FIND "${WD01_STUDIO}" "${FORBIDDEN}" FOUND)
    if(NOT FOUND EQUAL -1)
        message(FATAL_ERROR "WD01 contract: stock Wicked Editor UI leaked into Renegade Studio: ${FORBIDDEN}")
    endif()
endforeach()

message(STATUS "WD01 vegetation source contract passed")
